### ISSUE TITLE
Clarify J2EE necessity

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/Orienteer#130]
After I stumbled over the list of compatible J2EE containers including Jetty and Tomcat I looked through the code and didn't find one piece that needs J2EE. It's a Java Web application which matches the list of available containers as well (those wouldn't accept J2EE applications). IMO J2EE is not necessary to run the application and `README.md` can be adjusted.

**Comment by PhantomYdn** [comment]
Yea - you absolutely right. There is no need for J2EE. That was done especially, because unfortunately not all hostings allow to use j2ee containers or allow, but containers are not so advanced (for example Tomcat EE instead of JBOSS or WebLogic). And one more point: I tried to mix OrientDB and EJB - and because of quite significant difference in a methodology my try was not successful. There are lots of todo in OrientDB to make it more J2EE compatible: first of all that's JTA.
