### ISSUE TITLE
Document usage and precendence of system properties and configuration files at different locations

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/Orienteer#162]
I tried to figure out a system from the `lookupPropertiesURL` and `lookupFile` methods of `OrienteerModule`. I want to investigate a probale bug and I'm stuck at loading properties. I'm missing a default fallback, but rather than figuring out what should happen from the code I'd appreciate documentation (as general as possilbe). I guess it'd make sense to do that as a class comment in `OrienteerModule`.

**Comment by PhantomYdn** [comment]
Thanks! Will update JavaDoc.
But please help me understand your problem in details...

lookupPropertiesURL() and lookupFile() are doing pretty much the same: trying to find properties file to lood. Idea is following:

1) Check system property for directly specified filename. If it's there: use that file or URL
2) Otherwise it looks for required properties file from local directory and up

But let me note, that corresponding system property can be specified by code. For example there: StaticInjectorProvider (for tests) or in StartStandalone (to fallback to embedded configuration).

**Comment by krichter722** [comment]
> Will update JavaDoc.

Thanks.

> lookupPropertiesURL() and lookupFile() are doing pretty much the same: trying to find properties file to lood. Idea is following:

> 1) Check system property for directly specified filename. If it's there: use that file or URL
> 2) Otherwise it looks for required properties file from local directory and up

Adding that into javadoc would make me happy - I get it from the comment, but it's better placed into Javadoc; we might not be the only people working on Orienteer, might we ;) I'll explain the problem in a separate issue if I've trouble (because this one is just about the missing documentation).

**Comment by krichter722** [comment]
closed with 8594353b2a876b83f9c867624b5b113a36a29875 (commit message not recognized)
